name: scorm_master
description: Aula Cibermedida SCORM-Master
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  
  # Archivos
  file_picker: ^10.3.8
  csv: ^5.1.1
  path_provider: ^2.1.2 
  archive: ^3.6.1 
  xml: ^6.5.0
  path: ^1.9.0
  
  # Web & Utils
  universal_html: ^2.3.0
  uuid: ^4.5.2
  http: ^1.2.9
  web: ^1.0.0  # O la versiÃ³n mÃ¡s reciente
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  google_generative_ai: ^0.4.0
  flutter_markdown: ^0.7.2
  video_player: ^2.8.6
  just_audio: ^0.9.36
  youtube_player_iframe: ^5.1.2
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  
  # ðŸ”¥ LA CONFIGURACIÃ“N ESTABLE (TODO EN V10) ðŸ”¥
  flutter_quill: ^10.7.3 
  vsc_quill_delta_to_html: ^1.0.3            
  flutter_quill_delta_from_html: ^1.3.15     
  flutter_widget_from_html: ^0.15.3          
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

# ðŸ›‘ AQUÃ ESTÃ EL TRUCO DE MAGIA ðŸ›‘
# Esto obliga a Flutter a aceptar versiones aunque se queje
dependency_overrides:
  file_picker: ^10.3.8
  intl: any  # <--- ESTO ARREGLA EL ERROR DE VERSIÃ“N DE FLUTTER

flutter:
  uses-material-design: true
  assets:
    - assets/config/secrets.json
    - assets/config/
